version: '3'
services:
  flask_app:
    image: minha-app-flask
    build: .
    ports:
      - "5000:5000"
    networks:
      - monitoramento

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoramento

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoramento

networks:
  monitoramento: